### ISSUE TITLE
Compatibility with third-party checkouts

### ISSUE THREAD

**Issue by vovayatsyuk** [devromans/payment-fee#10]
Hi, I have an issue with incorrect fee calculating at firecheckout page.

The problem is that firecheckout calls for collect totals multiple times during one dispatch flow, and Brander_PaymentFee_Model_Sales_Quote_Address_Total_Fee::collect starts to calculate fee considering previously calculated value.

Part from [Brander_PaymentFee_Model_Sales_Quote_Address_Total_Fee class](https://github.com/devromans/payment-fee/blob/master/src/app/code/community/Brander/PaymentFee/Model/Sales/Quote/Address/Total/Fee.php#L39-L42):

```php
$exist_amount = $quote->getFeeAmount();
$fee          = $feeModel->getFee($address);
$balance      = $fee - $exist_amount;
```

I was wondering, do you have a use case when `$quote->getFeeAmount()` will actually return a non zero value?

For now, I fix the issue by omitting `$exist_amount` value:

```php
$balance      = $fee;
```

**Comment by priyaraj456** [comment]
Now grand total value is not consider the extra payment value for calculation.
