### ISSUE TITLE
Payment fee not shown in admin side

### ISSUE THREAD

**Issue by priyaraj456** [devromans/payment-fee#13]
Hlo...
I am totally new in magento . i place and test the "payment-fee" folder  in app, app/code, app/code/core, app/code/local, i couldn't find payment fee options in admin side. Actually where should i keep this payment-fee folder. plz help me...

**Comment by devromans** [comment]
Hello @priyaraj456, which Magento version you use?

**Comment by priyaraj456** [comment]
Magento ver. 1.9.3.9

**Comment by priyaraj456** [comment]
Magento ver. 1.9.3.9

**Comment by priyaraj456** [comment]
Thank you sir..  Problem solved. It was my mistake, i placed folder wrongly.

**Comment by priyaraj456** [comment]
Now i got an another error.

PayPal gateway has rejected request.The totals of the cart item amounts do not match order amounts (#10413: Transaction refused because of an invalid argument. See additional error messages for details).

This is because paypal is not consider this extra fee when find out the sum.
How can i solve this ?
