### ISSUE TITLE
Magento 2 Payment Fee.

### ISSUE THREAD

**Issue by mrkhoa99** [devromans/payment-fee#2]
Hello,

I'm going to follow the same logic of your module to build a Payment fee in Magento 2 version? Can I do this?

**Comment by devromans** [comment]
Hello, feel free :)

**Comment by mrkhoa99** [comment]
Thanks you!

**Comment by mrkhoa99** [comment]
I invite you to contribute to our module: https://github.com/mrkhoa99/boolfly_payment_fee/blob/master/README.md
